### ISSUE TITLE
Maven Central release

### ISSUE THREAD

**Issue by pschichtel** [squins/jekyll-jruby-maven#1]
It would be nice to have a release in the central repository to easily use this plugin.

**Comment by keesvandieren** [comment]
This repository is not the product itself, it only exists to reproduce a Windows bug in the Ruby JVM integration.

More info about this plugin is here: http://torquebox.org/development/maven-mechanics/

If you'd like to have it in the repo, ask torquebox for suppport.

**Comment by pschichtel** [comment]
Oh OK, thanks for the hint.

Am 11. Juni 2018 19:45:29 schrieb Kees van Dieren <notifications@github.com>:
